#!/bin/bash
su apache <<'EOF'
. /opt/data/ckan/pyenv/bin/activate
sources=`/opt/data/ckan/pyenv/bin/paster --plugin=ckanext-harvest harvester sources --config=/etc/kata.ini |grep "Source id:"|cut -c 12-`
for source in $sources;
do
    /opt/data/ckan/pyenv/bin/paster --plugin=ckanext-harvest harvester job $source --config=/etc/kata.ini >/dev/null 2>&1
done
/opt/data/ckan/pyenv/bin/paster --plugin=ckanext-harvest harvester run --config=/etc/kata.ini >/dev/null 2>&1
EOF
