#!/bin/bash
su apache <<'EOF'
. /home/ckan/pyenv/bin/activate
sources=`/home/ckan/pyenv/bin/paster --plugin=ckanext-harvest harvester sources --config=/etc/kata.ini |grep "Source id:"|cut -c 12-`
for source in $sources;
do
    /home/ckan/pyenv/bin/paster --plugin=ckanext-harvest harvester job $source --config=/etc/kata.ini
done
/home/ckan/pyenv/bin/paster --plugin=ckanext-harvest harvester run --config=/etc/kata.ini
EOF
